import 'dotenv/config';

export const {
    PORT,
    MYSQL_HOST,
    MYSQL_USER,
    MYSQL_PASS,
    MYSQL_DB,
    ADMIN_EMAIL,
    ADMIN_PASSWORD,
    ADMIN_FIRST_NAME,
    ADMIN_LAST_NAME,
    ADMIN_PHONE,
    ADMIN_DNI,
    SECRET,
    NODE_ENV,
    DOMAIN,
    SMTP_HOST,
    SMTP_PORT,
    SMTP_USER,
    SMTP_PASS,
    SMTP_EMAIL,
    CLIENT_URL,
    UPLOADS_DIR,
} = process.env;
